/**
 * The runtime-minted, single-use cleanup token (TEAR-03, D-08 to D-11).
 *
 * Mirrors `packages/core/src/receipts/checkpoint.ts`'s injected-key,
 * caller-supplied-`CryptoKey` discipline exactly -- `mintCleanupToken` NEVER
 * reads a key from disk/env, and reuses the SAME Ed25519 checkpoint key
 * `signCheckpoint` signs with (D-09): one runtime signing identity for
 * checkpoints and cleanup tokens. The wire shape is deliberately DIFFERENT
 * from `checkpoint.ts`'s detached `FlattenedSign` -- this is jose's
 * compact-JWT `SignJWT`/`jwtVerify` path (confirmed against the installed
 * `jose@6.2.12` `.d.ts` files), because the cleanup hook is an ordinary
 * bearer-token HTTP call, not a detached-signature verification scenario.
 *
 * Single-use (D-10) is enforced entirely by MINTING: the runtime generates a
 * fresh `jti` and a fresh token for every cleanup-hook attempt and never
 * re-presents one; "reject reuse" is the hook's own attested contract, not
 * something this module tracks. `CLEANUP_TOKEN_TTL_SECONDS` is a runtime
 * config constant (D-11) -- it is NEVER read from a manifest.
 */

import { SignJWT, jwtVerify } from "jose";
import type { CryptoKey } from "jose";

/**
 * Order-of-minutes per-attempt TTL (D-11) bounding the cleanup token's
 * replay window tightly. A runtime config value, never manifest-carried --
 * fresh mint per attempt (D-10) means a retry never fights an expired
 * token, it simply mints a new one.
 */
export const CLEANUP_TOKEN_TTL_SECONDS = 120;

/** The decoded, verified claim set a `cleanup:<lease_id>`-scoped token carries (D-08). */
export interface CleanupTokenClaims {
  readonly scope: string;
  readonly jti: string;
  readonly iat: number;
  readonly exp: number;
}

/**
 * Mints a single-use cleanup token (D-08 to D-11): a compact EdDSA JWT
 * scoped exactly `cleanup:<leaseId>`, carrying the caller-supplied `jti`
 * (fresh per attempt -- D-10, generated by the caller, e.g. `steps.ts`'s
 * `cleanup_hook` step, never by this function) and `iat`/`exp` derived from
 * `now` plus {@link CLEANUP_TOKEN_TTL_SECONDS}. `privateKey` MUST be the SAME
 * Ed25519 key `signCheckpoint` signs with (D-09) -- callers never construct
 * or load a second signing key for this purpose.
 */
export async function mintCleanupToken(
  leaseId: string,
  jti: string,
  now: number,
  privateKey: CryptoKey,
): Promise<string> {
  return new SignJWT({ scope: `cleanup:${leaseId}` })
    .setProtectedHeader({ alg: "EdDSA" })
    .setIssuedAt(now)
    .setExpirationTime(now + CLEANUP_TOKEN_TTL_SECONDS)
    .setJti(jti)
    .sign(privateKey);
}

/**
 * Reference-only verify (documentation shape): the REAL verification of a
 * cleanup token happens on the publisher's hook, entirely outside this
 * codebase -- this function exists so the runtime side of the contract is
 * concretely testable and so the mint/verify shapes stay symmetric, not
 * because any runtime code path calls it. Fail-closed: every failure mode
 * (wrong key, expired token, malformed claims, wrong `scope` prefix)
 * collapses to `null`, mirroring `checkpoint.ts`'s `verifyCheckpoint`
 * discipline -- jose's exception text is never forwarded (T-01-15, D-16).
 *
 * `now` is an OPTIONAL epoch-seconds override for `exp`/`nbf` evaluation
 * (passed to jose as `currentDate`) -- a real hook verifies against its own
 * wall-clock time, so production usage of this reference function omits it;
 * tests that mint and verify against an injected, non-wall-clock `now` (this
 * codebase's convention throughout) supply it so verification is evaluated
 * consistently with the same clock the token was minted against.
 */
export async function verifyCleanupToken(
  token: string,
  publicKey: CryptoKey,
  now?: number,
): Promise<CleanupTokenClaims | null> {
  try {
    const options = now === undefined ? { algorithms: ["EdDSA"] } : { algorithms: ["EdDSA"], currentDate: new Date(now * 1000) };
    const { payload } = await jwtVerify(token, publicKey, options);
    if (typeof payload.scope !== "string" || !payload.scope.startsWith("cleanup:")) return null;
    if (typeof payload.jti !== "string") return null;
    if (typeof payload.iat !== "number" || typeof payload.exp !== "number") return null;
    return { scope: payload.scope, jti: payload.jti, iat: payload.iat, exp: payload.exp };
  } catch {
    return null;
  }
}
