/**
 * PASETO v4.public hosted-license issuance (D-11, D-13, LIC-01).
 *
 * Composes `paseto@4.0.1`'s factory-composition API (`PublicProtocol` from
 * the root `paseto` module combining `SignFactory` from `paseto/v4/public`)
 * -- never the classic 3.x `V4.sign` static-namespace API. `exp` is always
 * set as an explicit RFC 3339 claim derived from the caller's already-clamped
 * `expEpochSeconds`; paseto's own `expiresIn` option is never used, since it
 * measures from paseto's internal now and cannot express the LIC-03
 * `min(now + defaultTTL, lease.expiresAt)` clamp the caller already applied.
 * `kid` is carried only in the token's footer -- authenticated but public,
 * non-secret (PITFALLS.md Pitfall 4) -- never as a claim.
 */

import { PublicProtocol } from "paseto";
import { SignFactory } from "paseto/v4/public";
import type { SecretKey } from "paseto/v4/public";

import { deriveImplicitAssertion } from "./implicit-assertion.js";

/** The custom claim carrying the manifest's `job.description` into the license (Claude's Discretion, D-13). */
export interface LicenseJobClaim {
  readonly description: string;
}

/** The custom claim carrying the manifest's entitlement bounds into the license (Claude's Discretion, D-13). */
export interface LicenseLimitsClaim {
  readonly max_actions: number;
  readonly actions_per_hour: number | null;
}

/** The three custom claims a hosted license carries alongside the registered `exp`/`iat`/`nbf`/`jti` (D-13). */
export interface LicenseClaims {
  readonly lease_id: string;
  readonly job: LicenseJobClaim;
  readonly limits: LicenseLimitsClaim;
}

const signProtocol = new PublicProtocol(SignFactory);

/** `{ kid }`, the token footer's only content -- authenticated but public/non-secret (D-13, Pitfall 4). */
interface LicenseFooter {
  readonly kid: string;
}

function encodeFooter(kid: string): Uint8Array {
  const footer: LicenseFooter = { kid };
  return new TextEncoder().encode(JSON.stringify(footer));
}

/**
 * Issues a PASETO v4.public license over `claims`, with `kid` carried in the
 * token's footer and the implicit assertion derived by the one shared
 * `deriveImplicitAssertion` (D-13). `exp` is set as an explicit claim
 * derived from the already-clamped `expEpochSeconds` -- never via paseto's
 * `expiresIn` option -- so callers (LIC-03's refresh clamp) fully control
 * the issued expiry. `nbf` is set to `now` (the license is valid
 * immediately); `iat` is generated by paseto from the same injected `now`.
 * `jti` defaults to a fresh random token identifier; a caller may pass a
 * fixed value for reproducible output (e.g. the license conformance vector).
 */
export async function issueLicense(
  secretKey: SecretKey,
  claims: LicenseClaims,
  kid: string,
  specVersion: string,
  now: number,
  expEpochSeconds: number,
  jti: string = crypto.randomUUID(),
): Promise<string> {
  const implicitAssertion = deriveImplicitAssertion(claims.lease_id, specVersion);
  const nowDate = new Date(now * 1000);
  const exp = new Date(expEpochSeconds * 1000).toISOString();
  const nbf = nowDate.toISOString();

  return signProtocol.Sign(
    secretKey,
    {
      lease_id: claims.lease_id,
      job: claims.job,
      limits: claims.limits,
      exp,
      nbf,
      jti,
    },
    {
      now: nowDate,
      addIssuedAt: true,
      footer: encodeFooter(kid),
      implicitAssertion,
    },
  );
}
