#!/usr/bin/env node
// Generates TypeScript types from spec/*.schema.json via json-schema-to-typescript,
// plus a schemas.ts module exporting the raw schema objects for Ajv to compile.
//
// Usage:
//   node scripts/codegen.mjs                 # regenerate committed output
//   node scripts/codegen.mjs --check          # exit 1 if committed output is stale
//   node scripts/codegen.mjs --check --schema-dir DIR  # check against schemas in DIR

import { compile } from "json-schema-to-typescript";
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
// packages/spec/scripts -> packages/spec -> packages -> repo root
const repoRoot = path.resolve(scriptDir, "..", "..", "..");
const packageRoot = path.resolve(scriptDir, "..");

const args = process.argv.slice(2);
const isCheck = args.includes("--check");
const schemaDirFlagIndex = args.indexOf("--schema-dir");
const schemaDir =
  schemaDirFlagIndex !== -1 && args[schemaDirFlagIndex + 1]
    ? path.resolve(args[schemaDirFlagIndex + 1])
    : path.join(repoRoot, "spec");

const outDir = path.join(packageRoot, "src", "generated");

const targets = [
  { schemaFile: "manifest.schema.json", typeName: "Manifest", outFile: "manifest.ts" },
  { schemaFile: "envelope.schema.json", typeName: "SignedEnvelope", outFile: "envelope.ts" },
];

function normalizeLineEndings(text) {
  return text.replace(/\r\n/g, "\n");
}

function writeOrCheck(outPath, content, stale, label) {
  if (isCheck) {
    const current = existsSync(outPath) ? readFileSync(outPath, "utf8") : "";
    if (normalizeLineEndings(current) !== normalizeLineEndings(content)) {
      stale.push(label);
    }
  } else {
    if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });
    writeFileSync(outPath, content);
  }
}

async function main() {
  const stale = [];
  const schemaObjects = {};

  for (const target of targets) {
    const schemaPath = path.join(schemaDir, target.schemaFile);
    const schemaText = readFileSync(schemaPath, "utf8");
    const schema = JSON.parse(schemaText);
    schemaObjects[target.schemaFile] = schema;

    // json-schema-to-typescript emits `type X = {...}` instead of
    // `interface X {...}` for any schema node carrying a top-level `allOf`
    // (even though the merged shape is a plain object either way, since
    // if/then conditional-required rules aren't expressible in TS types
    // regardless of whether allOf is present). Strip the root `allOf` for
    // TYPE GENERATION ONLY so the committed types stay a clean interface;
    // the real schema (with allOf intact) is what schemas.ts exports for
    // Ajv to compile and actually enforce at runtime.
    const typegenSchema = { ...schema };
    delete typegenSchema.allOf;

    const generated = await compile(typegenSchema, target.typeName);
    const outPath = path.join(outDir, target.outFile);
    writeOrCheck(outPath, generated, stale, target.outFile);
  }

  const manifestSchema = schemaObjects["manifest.schema.json"];
  const envelopeSchema = schemaObjects["envelope.schema.json"];

  const schemasContent =
    "/* eslint-disable */\n" +
    "/**\n" +
    " * This file was automatically generated by scripts/codegen.mjs.\n" +
    " * DO NOT MODIFY IT BY HAND. Instead, modify spec/manifest.schema.json or\n" +
    " * spec/envelope.schema.json, and run `pnpm codegen` to regenerate this file.\n" +
    " */\n\n" +
    `export const manifestSchema = ${JSON.stringify(manifestSchema, null, 2)};\n\n` +
    `export const envelopeSchema = ${JSON.stringify(envelopeSchema, null, 2)};\n`;

  const schemasOutPath = path.join(outDir, "schemas.ts");
  writeOrCheck(schemasOutPath, schemasContent, stale, "schemas.ts");

  if (isCheck && stale.length > 0) {
    console.error(`Generated types are stale: ${stale.join(", ")}`);
    console.error("Run `pnpm codegen` and commit the result.");
    process.exit(1);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
